create table books
(id bigint generated by default as identity,
 isbn varchar(255) not null unique,
 title varchar(255) not null,
 author varchar(255) not null,
 publisher varchar(255) not null,
 year_of_publication integer not null,
 primary key (id))
