create table customer
(customer_id bigint generated by default as identity,
 customer_name varchar(255) not null,
 email varchar(255) not null,
 phone varchar(255) not null,
 primary key (customer_id))
